# service configuration for our dockerized Rails app
app:

  # use the Dockerfile next to this file
  build: .

  # sources environment variable configuration for our app
  env_file: .env

  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV

  # makes the app container aware of the DB container
  links:
    - mysql

  # expose the port we configured Unicorn to bind to
  expose:
    - "3000"

# service configuration for our database
mysql:
 
  image: mysql:5.6
 
  env_file: .mysql-env

  # persist the database between containers by storing it in a volume
  volumes:
    - elogic-integration-mysql:/var/lib/mysql

# service configuration for our web server
web:

  # set the build context to the root of the Rails app
  build: .

  # build with a different Dockerfile
  dockerfile: config/containers/Dockerfile-nginx
  
  # makes the web container aware of the app container
  links:
    - app
  
  # expose the port we configured Nginx to bind to
  ports:
    - "80:80"