default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: mysql
  port: 3306
 
development:
  <<: *default
  database: elogic_integration_development
 
test:
  <<: *default
  database: elogic_integration_test
 
production:
  <<: *default
  database: elogic_integration_production