default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
 
development:
  <<: *default
  database: elogic_integration_development
 
test:
  <<: *default
  database: elogic_integration_test
 
production:
  <<: *default
  database: elogic_integration_production